# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cara Harshman
email:
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the personal portfolio site for me, Cara Harshman. I am slowly
  but steadily building the site with Jekyll. In the near future,
  caraharshman.me will be a home for blog posts, projects from content
  marketing at Optimizely, and other dabblings. Thanks for visiting!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://caraharshman.me" # the base hostname & protocol for your site
twitter_username: caraharshman

github_username:

# Build settings
markdown: kramdown
